### ISSUE TITLE
Installation Error [Win 10, Ruby 3.1.0 using RubyMine IDE]

### ISSUE THREAD

**Issue by KagemniKarimu** [corck/sia_skynet#2]
I have a recurring issue with a dependency/DLL while installing the gem, that results in the following errors:

``C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/ffi-1.15.5-x64-mingw-ucrt/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'libcurl': The specified module could not be found.\r (LoadError)
Could not open library 'libcurl.dll': The specified module could not be found.\r
Could not open library 'libcurl.so.4': The specified module could not be found.\r
Could not open library 'libcurl.so.4.dll': The specified module could not be found.\r
<internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- skynet (LoadError)
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Users/Admin/RubymineProjects/skynet_test/skynet.rb:1:in `<main>'``

**Comment by KagemniKarimu** [comment]
I am able to fix the issue manually by downloading, renaming, and placing `libcurl.dll` in the Ruby bin directory.  Is it possible for the gem itself to install this dll if it's missing on Windows?

**Comment by corck** [comment]
As I don't know much about Ruby on Windows I really don't know how Ruby on Windows works.... Happy to accept pull requests with improvements like this.
